name: Secret Scan

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

permissions:
  contents: read

jobs:
  block-env-files:
    name: Block committed .env files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fail if .env files are tracked
        shell: bash
        run: |
          set -euo pipefail
          if git ls-files | grep -E '^\\.env(\\..+)?$' | grep -v '^\\.env.example$' >/dev/null; then
            echo "❌ One or more .env files are tracked. Remove them and force-push after history purge."
            git ls-files | grep -E '^\\.env(\\..+)?$' | grep -v '^\\.env.example$' || true
            exit 1
          fi
          echo "✅ No tracked .env files detected"

  gitleaks-scan:
    name: Gitleaks Secret Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --verbose

